---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 8.11.2
  values:
    nodeExporter:
      serviceMonitor:
        relabelings:
          - sourceLabels: [__meta_kubernetes_pod_node_name]
            targetLabel: instance

    grafana:
      enabled: true
      defaultDashboardsEnabled: true
      ingress:
        enabled: true
        hosts:
          - grafana.k8s-test.jakob.soy
    alertmanager:
      ingress:
        enabled: true
        hosts:
          - alertmanager.k8s-test.jakob.soy
    prometheus:
      prometheusSpec:
        serviceMonitorSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
      ingress:
        enabled: true
        hosts:
          - prometheus.k8s-test.jakob.soy
