---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: demo
  namespace: demo
spec:
  releaseName: demo
  chart:
    git: https://github.com/stefanprodan/podinfo
    ref: v3.x
    path: charts/podinfo
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - demo.k8s.aws-test.jakob.soy
      path: /
