apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: aws-auth
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::XXXXXXXX:role/eksctl-XXXXXXXXXXXXX
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - custom:readonly
      rolearn: arn:aws:iam::XXXXXXXX:role/Developer
      username: custom:developer
      groups:
      - custom:developer
  mapUsers: |
    []
