apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test
  region: eu-central-1

iam:
  withOIDC: true

managedNodeGroups:
  - name: default-workers-v3
    instanceType: t3.medium
    desiredCapacity: 3
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
