---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  releaseName: jenkins
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: jenkins
    version: 1.9.21
  values:
    master:
      adminPassword: jenkinsAdmin
      installPlugins:
        - blueocean
      ingress:
        enabled: true
        hostName: jenkins.k8s-test.jakob.soy
      sidecars:
        configAutoReload:
          enabled: true
