apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: aws-auth
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::299619554958:role/eksctl-test-nodegroup-default-wor-NodeInstanceRole-Q000IGTFT5U4
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - custom:readonly
      rolearn: arn:aws:iam::299619554958:role/Developer
      username: custom:developer
  mapUsers: |
    []
